language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - "1.10"

script: GO15VENDOREXPERIMENT=1 go test -v $(go list ./... | grep -v /vendor/)

install:
  - go get gopkg.in/DATA-DOG/go-sqlmock.v1 
  - go get github.com/rafaeljusto/redigomock
